config/routes.rb
NeXtSight::Application.routes.draw do

  devise_for :users

  resources :users, :only => [ :show ]

  resources :albums do
    resources :pictures
    #resources :movies,   :controller => :documents
  end

  root :to => 'home#index'
end

app/models/album.rb
class Album < ActiveRecord::Base

  belongs_to :parent,     :class_name => 'Album'
  has_many   :sub_albums, :class_name => 'Album'

  has_many   :documents, :class_name => 'Document'

  validates :name, :presence => true

  def self.roots
    self.where(:parent_id => nil)
  end

  def pictures
    self.documents.where(:type => Picture.name)
  end

  def movies
    self.documents.where(:type => Movie.name)
  end

  def has_sub_albums?
    !self.sub_albums.empty?
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ProtectedController
  # GET /albums
  # GET /albums.json
  def index
    @albums = current_user.albums.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = current_user.albums.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = current_user.albums.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = current_user.albums.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = current_user.albums.build(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = current_user.albums.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = current_user.albums.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :ok }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= album.name %></td>
    <td><%= album.description %></td>
    <td><%= album.location %></td>
    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
    <td><%= link_to 'Destroy', album, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @album.name %>
</p>

<p>
  <b>Description:</b>
  <%= @album.description %>
</p>

<p>
  <b>Location:</b>
  <%= @album.location %>
</p>


<table>
  <tr>
    <th>Preview</th>
    <th>Name</th>
    <th>Description</th>
    <th>Tags</th>
    <th></th>
    <th></th>
  </tr>

<% @album.pictures.each do |picture| %>
  <tr>
    <td><%= link_to(image_tag(picture.photo.url(:thumb)), album_picture_path(@album, picture)) %></td>
    <td><%= picture.name %></td>
    <td><%= picture.description %></td>
    <td><%= picture.tags %></td>
    <td><%= link_to 'Edit', edit_album_picture_path(@album, picture) %></td>
    <td><%= link_to 'Destroy', album_picture_path(@album, picture), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New picture', new_album_picture_path(@album) %>
<hr />
<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>