config/routes.rb
NeXtSight::Application.routes.draw do

  devise_for :users

  resources :users, :only => [ :show ]

  resources :albums do
    resources :pictures
    #resources :movies,   :controller => :documents
  end

  root :to => 'home#index'
end

app/models/picture.rb
class Picture < Document

  has_attached_file :photo, {
      :styles => { :big => "800x800>", :medium => "300x300>", :thumb => "120x120>" },
      :url => "/system/pictures/:hash.:extension",
      :hash_secret => "36f4e442578658147f6fc4d9255126c166718641"
  }

  validates_attachment_presence :photo

  before_save :extract_exif

  protected
  def extract_exif
    self.exif = "ToDo"
  end

end

app/controllers/pictures_controller.rb
class PicturesController < DocumentsController

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = album.pictures.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = album.pictures.find(params[:id])

    respond_to do |format|
      format.html { }
      format.json { }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @picture = Picture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    @picture = album.pictures.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(params[:picture])
    @picture.album = album

    respond_to do |format|
      if @picture.save
        format.html { redirect_to album_picture_path(@album, @picture), notice: 'Document was successfully created.' }
        format.json { render json: @picture, status: :created, location: @picture }
      else
        format.html { render action: "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    @picture = album.pictures.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to album_picture_path(@album, @picture), notice: 'Document was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = album.pictures.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :ok }
    end
  end

end

app/views/pictures/_form.html.erb
<%= form_for([album, @picture], :html => { :multipart => true }) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% @picture.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <br/>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :tags %>
    <br/>
    <%= f.text_field :tags %>
  </div>

  <div class="field">
    <%= f.label :photo %>
    <br/>
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', album_picture_path(@album, @picture) %> |
<%= link_to 'Back', album_pictures_path(@album) %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table>
  <tr>
    <th>Preview</th>
    <th>Name</th>
    <th>Description</th>
    <th>Tags</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pictures.each do |picture| %>
  <tr>
    <td><%= image_tag picture.photo.url(:thumb) %></td>
    <td><%= picture.name %></td>
    <td><%= picture.description %></td>
    <td><%= picture.tags %></td>
    <td><%= link_to 'Show', album_picture_path(album, picture) %></td>
    <td><%= link_to 'Edit', edit_album_picture_path(album, picture) %></td>
    <td><%= link_to 'Destroy', album_picture_path(album, picture), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New picture', new_album_picture_path(album) %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', album_pictures_path(album) %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @picture.name %>
</p>

<p>
  <b>Description:</b>
  <%= @picture.description %>
</p>

<div>
  <%= image_tag @picture.photo.url(:big) %>
</div>

<p>
  <b>Tags:</b>
  <%= @picture.tags %>
</p>


<%= link_to 'Edit', edit_album_picture_path(album, @picture) %> |
<%= link_to 'Back', album_path(album) %>